/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspcdimagecolouring;

import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author pc
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        panel_image = new javax.swing.JPanel();
        button_negatifEffect = new javax.swing.JButton();
        button_orginialImage = new javax.swing.JButton();
        button_grayScale = new javax.swing.JButton();
        button_rotate = new javax.swing.JButton();
        button_levelSlicing = new javax.swing.JButton();
        button_tresholding = new javax.swing.JButton();
        button_contrast = new javax.swing.JButton();
        button_lowPassFilter = new javax.swing.JButton();
        button_highPassFilter = new javax.swing.JButton();
        button_highBoostFilter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        button_exit = new javax.swing.JButton();
        button_fileChooser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        text_filePath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        panel_image.setBackground(new java.awt.Color(255, 255, 255));
        panel_image.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout panel_imageLayout = new javax.swing.GroupLayout(panel_image);
        panel_image.setLayout(panel_imageLayout);
        panel_imageLayout.setHorizontalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        panel_imageLayout.setVerticalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        button_negatifEffect.setBackground(new java.awt.Color(0, 0, 0));
        button_negatifEffect.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_negatifEffect.setForeground(new java.awt.Color(0, 204, 204));
        button_negatifEffect.setText("Efek Negatif");

        button_orginialImage.setBackground(new java.awt.Color(0, 0, 0));
        button_orginialImage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_orginialImage.setForeground(new java.awt.Color(0, 204, 204));
        button_orginialImage.setText("Gambar Asli");
        button_orginialImage.setBorder(null);
        button_orginialImage.setBorderPainted(false);
        button_orginialImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_orginialImageActionPerformed(evt);
            }
        });

        button_grayScale.setBackground(new java.awt.Color(0, 0, 0));
        button_grayScale.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_grayScale.setForeground(new java.awt.Color(0, 204, 204));
        button_grayScale.setText("Grayscale");

        button_rotate.setBackground(new java.awt.Color(0, 0, 0));
        button_rotate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_rotate.setForeground(new java.awt.Color(0, 204, 204));
        button_rotate.setText("Rotate");

        button_levelSlicing.setBackground(new java.awt.Color(0, 0, 0));
        button_levelSlicing.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_levelSlicing.setForeground(new java.awt.Color(0, 204, 204));
        button_levelSlicing.setText("Level Slicing");

        button_tresholding.setBackground(new java.awt.Color(0, 0, 0));
        button_tresholding.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_tresholding.setForeground(new java.awt.Color(0, 204, 204));
        button_tresholding.setText("Tresholding");

        button_contrast.setBackground(new java.awt.Color(0, 0, 0));
        button_contrast.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_contrast.setForeground(new java.awt.Color(0, 204, 204));
        button_contrast.setText("Contrast");

        button_lowPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        button_lowPassFilter.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_lowPassFilter.setForeground(new java.awt.Color(0, 204, 204));
        button_lowPassFilter.setText("Low Pass Filter");

        button_highPassFilter.setBackground(new java.awt.Color(0, 0, 0));
        button_highPassFilter.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_highPassFilter.setForeground(new java.awt.Color(0, 204, 204));
        button_highPassFilter.setText("High Pass Filter");

        button_highBoostFilter.setBackground(new java.awt.Color(0, 0, 0));
        button_highBoostFilter.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_highBoostFilter.setForeground(new java.awt.Color(0, 204, 204));
        button_highBoostFilter.setText("High Boost Filter");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("TUGAS PCD IMAGE ENHANCEMENT COLOURING");

        button_exit.setBackground(new java.awt.Color(0, 0, 0));
        button_exit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_exit.setForeground(new java.awt.Color(0, 204, 204));
        button_exit.setText("Exit");
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        button_fileChooser.setBackground(new java.awt.Color(0, 0, 0));
        button_fileChooser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        button_fileChooser.setForeground(new java.awt.Color(0, 204, 204));
        button_fileChooser.setText("Choose File");
        button_fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fileChooserActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setToolTipText("File.jpeg");

        text_filePath.setFocusable(false);
        text_filePath.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_orginialImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_negatifEffect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_grayScale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_rotate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_levelSlicing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_contrast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_tresholding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_lowPassFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_highPassFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_highBoostFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(button_fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(text_filePath, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_orginialImage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_negatifEffect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_grayScale)
                        .addGap(18, 18, 18)
                        .addComponent(button_rotate)
                        .addGap(18, 18, 18)
                        .addComponent(button_levelSlicing)
                        .addGap(18, 18, 18)
                        .addComponent(button_contrast)
                        .addGap(18, 18, 18)
                        .addComponent(button_tresholding)
                        .addGap(18, 18, 18)
                        .addComponent(button_lowPassFilter)
                        .addGap(18, 18, 18)
                        .addComponent(button_highPassFilter)
                        .addGap(18, 18, 18)
                        .addComponent(button_highBoostFilter))
                    .addComponent(panel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_exit)
                        .addComponent(button_fileChooser)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_filePath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_orginialImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_orginialImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_orginialImageActionPerformed

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
       
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want to exit the program?", "Exit Program Message Box",
                        JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();
                }
            
//        System.exit(0);
//        dispose();
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fileChooserActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        text_filePath.setText(filename);
    }//GEN-LAST:event_button_fileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_contrast;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_fileChooser;
    private javax.swing.JButton button_grayScale;
    private javax.swing.JButton button_highBoostFilter;
    private javax.swing.JButton button_highPassFilter;
    private javax.swing.JButton button_levelSlicing;
    private javax.swing.JButton button_lowPassFilter;
    private javax.swing.JButton button_negatifEffect;
    private javax.swing.JButton button_orginialImage;
    private javax.swing.JButton button_rotate;
    private javax.swing.JButton button_tresholding;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_image;
    private javax.swing.JTextField text_filePath;
    // End of variables declaration//GEN-END:variables
}
